var GAME_LEVELS = [
  ["                                                                                ",
   "       xxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "       x           xxxx                                                        x",
   "       x                                                                       x",
   "       x                                                                       x",
   "       x                                                                       x",
   "  xxxxxx                                              o                        x",
   "  x                                                      xx                    x",
   "  x                                                                            x",
   "  x                                           o            xx                  x",
   "  x                                       xxxxx                                x",
   "  x                                                            xx       xxx    x",
   "  x                   o                       o o                              x",
   "  x                 xxxx                        x!!!!!!x                       x",
   "  x             xxxx                          x x!!!!!!x                     o x",
   "  x          xxx      o   x         s       x x x!!!!!!x                     f x",
   "  x  @       x       x     xx      xxx    x x x x!!!!!!x   g                xx x",
   "  xxxxx  xxxxx       xxxxxxxxxx!!!!!!!!!xxxxxxxxx!!!!!!xxxxxxxx   xxx   xxxxxxxx",
   "                              x!!!!!!!!!x       x!!!!!!x        yyx!!!!!!!!!!!x ",
   "                              x!!!!!!!!!x       x!!!!!!x       xxxx!!!!!!!!!!!x ",
   "                              x!!!!!!!!!x       x!!!!!!x          x!!!!!!!!!!!x ",
   "                              xxxxxxxxxxx       x!!!!!!x          xxxxxxxxxxxxx ",
   "                                                xxxxxxxx                        ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                         xxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                          v                                       ",
   "                                                   x ! x                                                          ",
   "                                                   x ! x                                                          ",
   "                                                   x v x                     x x         x x                      ",
   "                                                                                      x                           ",
   "                                                                                           x                      ",
   "                                                                                                                  ",
   "                                                    o  o     x   x                                                ",
   "                             xxx        o            s       x o x         o             o o                      ",
   "                       x   x          o             xxxxxxxxxxxxxxxxx    x   x   xxxxxxxxx   o                    ",
   "              o      x o x          xxx            x       x   x   x               x           o    o             ",
   "     @ o      x         x        x   x                x                             xxxxxx f xxxxxx               ",
   "    xxxx      x         x       x                   o   x              x   xxxxx   xxxxxx  x!x                    ",
   "    x x xx                     xx o xx         xx     x                                                           ",
   "!!!!x x!!xxx o                               x x                      x                                           ",
   "!!!!x x!!!xxx                xxx           xxx     x  xxx xx  o o  xx                                             ",
   "!!!!x x!!!!xxxx   o  g  o  o                  !!  o x !!       x           xx     xx                              ",
   "!!!!x x!!!!!!!!xxxxxxxxxxxxxx         x                      xx!x!!!!xx  !                                        ",
   "!!!!x x!!!!!!x         x!!!!!xx   o   xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                            o ",
   "  xxx                                                                                       o      x  x!!  xxx",
   "  x x                                           o  x  x      x                                   x         x x",
   "  x                                             x      o                            o          x              ",
   "  x                                           x    xxxxxx     x                   x          x               x",
   "  x                                         x                   x               x       o   x !!!!!!!!!!     x",
   "  x             s                         x                           ooo     x         x x   !!!!!!!!!!     x",
   "  x           o x                   o o x                         xxxxxxxxxxxx                  !!!!!!     x  ",
   "  x          x            xx          x                                                          !!!!!     x  ",
   "  x           x    o       x o  xxx    x                     x                                    !!!      x  ",
   "  x            x            xxxxxxxxxxxxx  x    x    x                                  x          !       x  ",
   "  x      @              g    x           x!!!    !!!!!x    x!!!!x    xx   xx    x!!!! o  !!!            f o x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
   ["                                                                                                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "     x       x      xxxxxxx    x     x     x      x   xxxxxx   x x      x    xx                               ",
   "     xxx   xxx      x     x    x     x     x      x     xx     x   x    x    xx                               ",
   "        x x         x     x    x     x     x      x     xx     x    x   x    xx                               ",
   "         x          x     x    x     x     x  xx  x     xx     x     x  x                                     ",
   "         x          xxxxxxx    xxxxxxx     x x  x x   xxxxxx   x      x x    xx                               ",
   "                                                                                                              ",
   "    @ o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o f           ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          ",
   "                                                                                                              "],


];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
